### ISSUE TITLE
Removing index.html and styles folder

### ISSUE THREAD

**Issue by nicolas-dular** [thoughtbot/ember-cli-rails#165]
As I understand it right: the index.html isn't necessary?
I just have to put in: `<%= include_ember_script_tags :frontend %>` into my `.erb` file. 

So why do I need the index.html file in the ember-cli app if I don't use it?
I can't remove it - get an error: `ENOENT, no such file or directory` 

Also: Is it possible to remove the styles folder? (This is probably more an ember-cli thing). I compile the sass through the asset pipeline, so I don't need styles in ember

**Comment by fullofcaffeine** [comment]
+1 for removing the index.html in the ember app folder. It's very confusing, actually.

**Comment by alexanderjeurissen** [comment]
I'm currently migrating from ember-rails to ember-cli using ember-cli-rails, however sometimes when I checkout another branch then come back to my ember-cli-rails branch I get build errors stating that there is no `styles` directory in the `app` folder.

I tried removing the include tag for the styles:
```
<%= include_ember_stylesheet_tags :learning_spaces
```

but somehow ember-cli-rails keeps checking the presence of the styles folder and won't build without it. I'm not planning on moving the styles out of the asset pipeline as of yet. so this is kind of annoying now i have to place a placeholder file in the styles directory otherwise it won't get tracked by Git.

**Comment by meleyal** [comment]
+1

**Comment by alexanderjeurissen** [comment]
@rwz any update on this ? what is your take on this issue ?

**Comment by alexanderjeurissen** [comment]
this is a screenshot of the error while building: (I'm using foreman to start both the rails and ember environment)
![screen shot 2015-09-24 at 15 54 37](https://cloud.githubusercontent.com/assets/1220084/10075202/cb860bde-62d4-11e5-9fd5-864d3964c85e.png)

as can be seen, the error occurs while symlinking the directories: `node_modules/ember-cli/node_modules/symlink-or-copy/index.js:63:26`

**Comment by olivierobert** [comment]
+1

**Comment by seanpdoyle** [comment]
Given the new direction this project has taken in the last month, [we'll be **requiring** the presence of the EmberCLI-generated `index.html`](https://github.com/thoughtbot/ember-cli-rails#configuring-the-ember-controller).

As such, we'll be closing this issue.

There's been a lot of movement on this repo recently.

Could you try out version [0.5.3](https://rubygems.org/gems/ember-cli-rails/versions/0.5.3) and verify that you're still having the same issues.
