### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by joshpfosi** [thoughtbot/ember-cli-rails#190]
Hi I followed the set up instructions in the README closely. My application is set up under a single root directory like:

```
shearwater
  -- rails
  -- ember
```

So my config file is:

```ruby
EmberCLI.configure do |config|
  config.app :shearwater, path: "#{Rails.root}/../ember/", build_timeout: 100
end
```

with an `index.html.erb`:

```erb
<%= include_ember_script_tags :shearwater %>
<%= include_ember_stylesheet_tags :shearwater %>
```

However, when loading my app, Ember assets cannot be found:

<img width="1346" alt="screen shot 2015-07-31 at 10 11 57 am" src="https://cloud.githubusercontent.com/assets/3605462/9009062/9d689d54-376c-11e5-891b-d70cf2e7549e.png">

What am I missing?

Thanks.

**Comment by clov3rly** [comment]
I'm having what I believe to be the same issue with the same directory structure as @joshpfosi. It appears that relative links within my app css are 404ing, as ember-cli-rails is serving the stylesheets from `http://localhost:3000/assets/<app-name>/<css-filename>.<hash>.css?body=1`, while ember serves them from `http://localhost:4200/assets/<css-filename>.css`

My CSS is then referencing font files like so: 
`../fonts/<font-name>.woff`

The extra directory that ember-cli-rails has inserted then means the browser tries to find these font files at `http://localhost:3000/assets/font/<font-name>.woff` instead of `http://localhost:3000/font/`.

Where it would find them, as I've symlinked the rails public directory to the ember dist directory. 

As the font files are being imported by a third-party plugin, I'm struggling to find a work around right now...

**Comment by seanpdoyle** [comment]
@joshpfosi @clov3rly could you both please try following the instructions here: https://github.com/thoughtbot/ember-cli-rails/issues/30#issuecomment-154768936

posting back in this issue with your results?

**Comment by seanpdoyle** [comment]
I think https://github.com/thoughtbot/ember-cli-rails/issues/30#issuecomment-154768936 should resolve the errors described in this issue.

If you try that approach and run into trouble, please post here and I'll reopen.
