### ISSUE TITLE
Mirage and ember-cli-rails : unable to mock api calls

### ISSUE THREAD

**Issue by benoittgt** [thoughtbot/ember-cli-rails#223]
Hello

I've first ask to @samselikoff for this issue but it seems more related to what ember-cli-rails do.

Console when running test with `ember test --server` return me this :
```
Mirage: Your Ember app tried to GET 'http://www.lvh.me:3000/api/front/696/users?page=1&per=25', but there was no route defined to handle this request. Define a route that matches this path in your mirage/config.js file. Did you forget to add your namespace?
```

My *config.js* look like this : 
```javascript
export default function() {
  this.urlPrefix = 'http://lvh.me:3000';
  this.namespace = '/api/front'; 

  this.get('/696/**', function(db, request) {
    return {
      data: {
        type: 'users',
        id: id,
        attributes: db.users
      }
    };
  })
}
```

I try also with `this.get('/696/users/**', function..` and a really simple route handler :

```javascript
export default function() {
  this.get('http://www.lvh.me:3000/api**');
}
```

I just have this in my `environment.js` : 
```javascript
  if (environment === 'development') {
    ENV['ember-cli-mirage'] = {
      enabled: false
    }
``` 

Any idea?

Apparently @seanpdoyle already manage to do [some stuff with mirage](https://github.com/thoughtbot/ember-cli-rails/pull/167)

**Comment by seanpdoyle** [comment]
@benoittgt thanks for opening this issue.

Could you clarify which environment you're seeing this problem? You mentioned an error while running `ember test --server`, and you've mentioned configuring `ENV['ember-cli-mirage'].enabled = false` in development.

`ember-cli-rails` and `ember test` are two separate processes that don't know anything about each other. 

Where do you see `ember-cli-rails` fitting into this?

Are you trying to configure a [passthrough](http://www.ember-cli-mirage.com/docs/v0.1.x/server-configuration/#passthrough) so that requests are forwarded to the Rails backend? If so, I think you're looking for `this.passthrough` instead of `this.get`.

However, by the looks of your `this.get('/696/**', function(db, request) { // ... });` block, you're using Mirage to mock out the Rails server.

Although I've never tried it personally, if you're interested in configuring a `this.passthrough` to the Rails server, you can try [running Ember's tests through Rails](https://github.com/thoughtbot/ember-cli-rails#ember-test-suite).

I'm closing this, as I don't think it's related to `ember-cli-rails`, but feel free to let me know how things turn out. I'm willing to re-open it if you can show that `ember-cli-rails` is the problem.

**Comment by benoittgt** [comment]
Thanks @seanpdoyle for your answer. I'm trying to test my ember app without calling my rails api. 

For the ember environment I'm under testing, for rails it's under development, but has you mention it is not related.

I will keep digging into it and stop thinking about ember-cli-rails.

Thanks for your help.

**Comment by seanpdoyle** [comment]
Good luck!

Feel free to comment here with your findings.

**Comment by benoittgt** [comment]
I finally nearly succeed to fix the problem but I get [a new one with i18n asset](https://github.com/samselikoff/ember-cli-mirage/issues/327). I'm quite lost because i18n assets are in `myrailsproject/assets/javascript/i18n.js` and I'm using [i18n-js](https://github.com/fnando/i18n-js). For me I18n are define when the app is build by rails. I'm maybe wrong.
