### ISSUE TITLE
Ember baseUrl is repeated twice in the url when different from root url

### ISSUE THREAD

**Issue by olivierobert** [thoughtbot/ember-cli-rails#310]
The Ember app is configured to be accessed at '/app', but going to this url redirect to '/app/app/'. 

![backend](https://cloud.githubusercontent.com/assets/696529/11387033/88a3ab40-9359-11e5-8e39-b14e7273bd60.png)

This issue can be replicated in [this repo](https://github.com/olivierobert/ember-cli-rails-bugs/tree/bug/redundant-app-url) which has a bare installation of Rails and Ember CLI.

The issue is happening with v0.5.5 and was not happening in prior versions (tested with v0.3.5 in a current project).

**Comment by seanpdoyle** [comment]
@olivierobert thanks for bringing this to our attention!

Also, thanks for linking a minimal repo to reproduce the bug. Since the repo is EmberCLI-only, what can we assume about the rails-side of things? 

Are you using `mount_ember_app`?

Are you rendering with the helper tags, or `render_ember_app`?

What are your initializer configurations?



@drapergeek this appears to be similar to what used to happen on your latest Ember project.

A lot has changed in `ember-cli-rails` since then, but do you remember how your issue was resolved?

**Comment by seanpdoyle** [comment]
@olivierobert I've been able to resolve the bug here:

https://github.com/olivierobert/ember-cli-rails-bugs/pull/1

But since the repo doesn't have the Rails-side, I'm not sure if the resolution is helpful and fits your real-world use case.

**Comment by seanpdoyle** [comment]
I'll also point out that the steps taken to resolve your issue go against the guidance provided in the README.

If that bug-fix works for you, I'll correct the README.

**Comment by drapergeek** [comment]
>@drapergeek this appears to be similar to what used to happen on your latest Ember project.

>A lot has changed in ember-cli-rails since then, but do you remember how your issue was resolved?

Sadly, it wasn't "resolved", I changed the setup to not require a base URL.

**Comment by olivierobert** [comment]
@seanpdoyle Removing the baseUrl config from the router did it. So this issue is closed but as you suggested it goes against the configuration stated in the README.

My bad for not pushing the Rails part. It's done now: https://github.com/olivierobert/ember-cli-rails-bugs

**Comment by seanpdoyle** [comment]
@olivierobert thanks for seeing this through to the end.

I've opened a PR to update the README: 

https://github.com/thoughtbot/ember-cli-rails/pull/312

Could you please provide some feedback?
