### ISSUE TITLE
undefined method `render_ember_app' for #<#<Class:0x00...

### ISSUE THREAD

**Issue by robertlandreaux** [thoughtbot/ember-cli-rails#320]
First of all, thank you to all who have made this gem possible. Without it, full integration tests were taking way too long.

I am getting this error after starting up the rails server and trying to load `localhost:3000`:

undefined method `render_ember_app' for #<#<Class:0x00...

I have read through the documentation thoroughly and must be missing something. You can view my project at https://github.com/robertlandreaux/gradejoyV3.

**Comment by seanpdoyle** [comment]
@robertlandreaux thanks for opening this issue, and an EXTRA thanks for linking to the repository!

The issue is caused by your `IndexController` extending from `ApplicationController`, and your `ApplicationController` extending from `JSONAPI::ResourceController`.

Currently, the gem includes [the helpers](https://github.com/thoughtbot/ember-cli-rails/blob/7badc2581e0158bb8017cf5a24a39ea8d50b77df/app/helpers/ember_rails_helper.rb) into [ActionController::Base](https://github.com/thoughtbot/ember-cli-rails/blob/7badc2581e0158bb8017cf5a24a39ea8d50b77df/lib/ember_cli/engine.rb#L13).

Since your `ApplicationController` and its descendants are serving JSON, and your `IndexController` is serving HTML, I recommend your `IndexController` inherit from `ActionController::Base`.

**Comment by seanpdoyle** [comment]
This is (in effect) a duplicate of https://github.com/thoughtbot/ember-cli-rails/issues/321

**Comment by robertlandreaux** [comment]
@seanpdoyle Thank you so much!
