### ISSUE TITLE
Content Security Policy Headers?

### ISSUE THREAD

**Issue by campbecf** [thoughtbot/ember-cli-rails#425]
How would you recommend sending Content Security Policy headers on the index.html request?

**Comment by campbecf** [comment]
When using ember-cli-content-security-policy and ember-cli-rails it seems to work if you set the CSP to use meta tags, but not headers. Is this a conflict between the two packages?

**Comment by seanpdoyle** [comment]
@campbecf `ember-cli-rails` doesn't currently support setting response headers for `index.html` requests -- I'm not sure how that should be implemented.

Do you know how `ember-cli-content-security-policy` handles that, since `ember build -e production` creates a directory of static files (therefore can't notify the serving server of response headers)?

In the short term, I'd recommend using meta tags for CSP.

**Comment by campbecf** [comment]
@seanpdoyle I'm not aware, but I can look into it. Thanks for the response. I'll reopen if I find anything worthwhile.
