### ISSUE TITLE
Moving away from baseURL (deprecated) for mounting on path other than /

### ISSUE THREAD

**Issue by nruth** [thoughtbot/ember-cli-rails#446]
I'd like to flag this as a problem and start a discussion about what could be done to fix it.

We deploy our app at `/sim` rather than `/` because `/` is where our Rails app lives (they coexist).
Currently we're able to do this using the `to` option of `mount_ember_app`, and setting a `baseURL` in ember-cli's environment.

Unfortunately this breaks SVGs, and it turns out is now deprecated in EmberCLI.
http://emberjs.com/blog/2016/04/28/baseURL.html

It seems the way forward is to use `rootURL` in EmberCLI, and prefix the asset links instead of using a base tag.

Can `include_ember_script_tags` and `include_ember_stylesheet_tags` be modified to support this? Could they take a path prefix argument, or even figure it out from the `mount_ember_app` `to` option?

**Comment by nruth** [comment]
Or will `render_ember_app` handle this, so long as the ember-cli app is correctly configured?

**Comment by seanpdoyle** [comment]
@nruth I'm sorry that this issue has sat for so long.

I'm embarrassed to admit that I'm a bit out of touch with more recent EmberCLI developments, particularly the removal of Ember's dependency on `<base>` tags.

My understanding is that configuring `rootURL` affect's Ember's runtime behavior, but doesn't affect the compiled output.

If that assumption is true, I don't think that `include_ember_script_tags` and `include_ember_stylesheet_tags` helpers could be affected by a `rootURL` declaration, since they serve the compiled asset files without Rails-side intervention.

> Could they take a path prefix argument,

[They already do](https://github.com/seanpdoyle/ember-cli-rails-assets/commit/23f9425dda1e4d6c0d50c22de6330743ed4489d2)! 

Does that help resolve your issue?

> Or will `render_ember_app` handle this, so long as the ember-cli app is correctly configured?

The `include` helpers and `render_ember_app` helpers are completely unrelated and independent of one another, since the `render_ember_app` helper serves the EmberCLI-generated `index.html` output, and the `include` helpers serve the EmberCLI-generated asset files only.

To answer your question, though, assuming that `ember-cli` is properly configured, everything should Just Work :tm:, as `render_ember_app` defers almost all responsibility to EmberCLI.

**Comment by nruth** [comment]
Hi Sean
Thanks for the detailed reply!

We don't have any problems right now with this so I'm going to close the issue. Sorry I forgot about it.

Our current install (on a subpath, with working SVGs) is using an `ember-cli-replace` hack to rewrite the asset paths (in ember-cli) until we can upgrade to an ember-cli version with official rootURL support.

I'll come back to your post when we upgrade as there's probably some code we can delete from our app.
