### ISSUE TITLE
No `ember-cli` executable found for `frontend`.

### ISSUE THREAD

**Issue by QTTT** [thoughtbot/ember-cli-rails#448]
I use:
OS 7 32bit
ember-cli: 2.5.0
node: 4.4.4
rails: 4.2.6
ember-cli-rails-0.7.3

have error:
No `ember-cli` executable found for `frontend`.

Install it:

    $ cd D:/Desktop_Project/ARDT/ExampleRuby/ember-rails-example/frontend
    $ npm install

I try delete node_modules in frontend then run npm install, but haven't resolved this error.

**Comment by seanpdoyle** [comment]
Thanks for opening this issue.

This issue doesn't follow the [contributing guidlelines](https://github.com/thoughtbot/ember-cli-rails/blob/master/CONTRIBUTING.md#reporting-an-issue), so I'm temporarily closing it.

Please update your issue by filling out [the issue template](https://github.com/thoughtbot/ember-cli-rails/blob/master/.github/ISSUE_TEMPLATE.md), so that this project's maintainers have a more context when triaging your issue.
