### ISSUE TITLE
Using ember-cli-rails on Windows Subsystem for Linux

### ISSUE THREAD

**Issue by kayakyakr** [thoughtbot/ember-cli-rails#493]
Playing around with Bash for Windows and trying to get my rails project up and running.

Latest windows build (14942) comes with inotify, so file system watchers now work. That means that this is actually possible! Mostly. Sorta.

Currently at a bit of a loss and trying to hunt down one blocker:

When I modify a file the first time, it rebuilds (albeit slowly) through the watcher. The second time, it sees that the file changed (gives me a notification that it changed) but never builds the new file. Have to restart the server to get it to build again.

I can do some heavy debugging, but was hoping someone had some ideas on which direction I should look.

**Comment by seanpdoyle** [comment]
@kayakyakr thanks for opening this issue!

`ember-cli-rails` shouldn't be doing much with filesystem watching. Instead, it relies on the `ember-cli` toolchain.

I think this would be a better issue on the [`ember-cli/ember-cli`](https://github.com/ember-cli/ember-cli/issues) repository.

I'm going to close this issue for now. If it turns out that it's an `ember-cli-rails` issue, please say so and we'll reopen this.

**Comment by kayakyakr** [comment]
Yeah, I've got a thread open over there as well: https://github.com/ember-cli/ember-cli/issues/6338

ember-cli's not running (for me) quite yet, so haven't been able to isolate and see if that side of the toolchain works or not.

**Comment by eriktrom** [comment]
https://github.com/ember-cli/ember-cli/issues/6338 has been fixed, fyi

**Comment by kayakyakr** [comment]
Not exactly @eriktrom. One issue has been fixed, but that issue had a workaround already. What was fixed did not have anything to do with the current blocking issue.
