### ISSUE TITLE
ember cli-rails as dependency rather than a devDependency?

### ISSUE THREAD

**Issue by stripedpumpkin** [thoughtbot/ember-cli-rails#506]
Wondering why 

`heroku config:set NPM_CONFIG_PRODUCTION=false`

Would there be an issue separating devDependencies from Dependencies and treating ember-cli-rails as a normal dependency (and leaving the heroku flag at true)? In general there could be a few devDependencies that need not be included in the prod build.

**Comment by seanpdoyle** [comment]
Unfortunately, this was a workaround to ensure that [`npm` installed `node_modules/ember-cli/bin/ember`](https://github.com/thoughtbot/ember-cli-rails/blob/85600ba7d4dc16c873148ef345a7f9069fe9f4ec/lib/ember_cli/path_set.rb#L40), so that the EmberCLI process had access to the executable.

This code hasn't changed in [almost a year](https://github.com/thoughtbot/ember-cli-rails/blame/85600ba7d4dc16c873148ef345a7f9069fe9f4ec/lib/ember_cli/path_set.rb#L40), which is eons in JS-time.

Do you know if newer versions of NPM require a similar workaround?

**Comment by seanpdoyle** [comment]
@stripedpumpkin you are correct, `bower` should be [declared as a `dependencies` value, not a `devDependencies` value](https://devcenter.heroku.com/articles/troubleshooting-node-deploys#ensure-you-aren-t-relying-on-untracked-dependencies) in the root level `package.json`.

The original suggestion stems from a misunderstanding of how NPM managed local executables.

I'm closing this for now, and will follow it up with a change to the documentation.

THANK YOU!

**Comment by seanpdoyle** [comment]
@stripedpumpkin related: https://github.com/thoughtbot/ember-cli-rails/pull/507
